added react-toastify for showing errors
jeffslofish/open-source-help-wanted pull request #56
Opened 2022-08-23 18:18 UTC by mngagan

showing toastify messages when getting any error from services

2022-08-23 18:50 UTC, jeffslofish requested changes
Thanks for this! Can you just address the one comment I made? Thanks!

2022-08-23 18:50 UTC, jeffslofish commented on src/components/Main.js
> +          {false && githubContext.errorMessage.length > 0 && ( // fix for issue 51 https://github.com/jeffslofish/open-source-help-wanted/issues/51
Can you just remove all this code that never executes? (Lines 416-418)

2022-08-24 14:12 UTC, mngagan commented
> done

2022-08-24 15:30 UTC, merged

2022-08-24 15:31 UTC, jeffslofish commented
Thanks! 👍