added some seo friendly meta tags to website
jeffslofish/open-source-help-wanted pull request #74
Opened 2022-10-11 09:51 UTC by coderelay2020

this is just a small thing related to SEO there is more to it

2022-10-11 09:53 UTC, coderelay2020 commented
#46 issue - added some seo friendly meta tags to website

2022-10-11 22:02 UTC, jeffslofish requested changes
Hi @coderelay2020, I am getting this error when I run the code:


Request from 127.0.0.1: GET /assets/icons/favicon.ico
Response with status 500 in 1 ms.
Error during invocation:  Error: Cannot find module '/Users/jeffreyfisher/Code/open-source-help-wanted/functions/assets'
Require stack:
- /Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/netlify-lambda/lib/serve.js
- /Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/netlify-lambda/bin/cmd.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/netlify-lambda/lib/serve.js:122:17
    at Layer.handle [as handle_request] (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:138:14)
    at Route.dispatch (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/express/lib/router/index.js:284:15 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/netlify-lambda/lib/serve.js',
    '/Users/jeffreyfisher/Code/open-source-help-wanted/node_modules/netlify-lambda/bin/cmd.js'
  ]
}

And I get this in the console:

GET http://localhost:3000/assets/icons/favicon.ico 500 (Internal Server Error)

2022-10-12 09:47 UTC, coderelay2020 commented on src/App.tsx
> +          <meta name="twitter:site" content="@teladochealth" />
I have resolved the issue.
I updated locally but forgot push sorry for the inconvenience

2022-10-12 16:53 UTC, merged

2022-10-12 16:53 UTC, jeffslofish commented
@coderelay2020 Thank you, it is now merged!